#!/usr/bin/env python3
"""Render an exact, legible Signature facilities legend alongside the original plan.

Input: page 7 (printed pages 11–12) of CapitaLand's public Main Brochure:
https://www.capitaland.com/sites/lumihanoi/resources/wp-content/uploads/2024/07/Capitaland-Lumi-Main-Brochure.pdf
The landscape artwork is preserved. Vietnamese legend text is typeset again;
no buildings, facilities, marker positions, or dimensions are generated by AI.
"""
from __future__ import annotations

import argparse
from io import BytesIO
from pathlib import Path

import fitz
from PIL import Image
from reportlab.lib.colors import HexColor
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

ROOT = Path(__file__).resolve().parents[1]
SOLE_OUTDOOR = [
    (1, 'Cổng Sole'), (2, 'Sảnh đón'), (3, 'Vườn Sole'),
    (4, 'Bể bơi Resort Sole'), (5, 'Sân tắm nắng'), (6, 'Chòi Thư Thái'),
    (7, 'Vườn BBQ Sole'), (8, 'Bể bơi Cầu Vồng'), (9, 'Sân nghỉ Cầu Vồng'),
    (10, 'Sân chơi nước Phiêu Lưu'), (11, 'Sân chơi Sáng Tạo'),
    (12, 'Chòi Niềm Vui'), (13, 'Chòi Vui Nhộn'), (14, 'Vườn Nắng Mai'),
    (15, 'Khu phố thương mại Sole'),
]
SOLE_INDOOR = [
    (16, 'Sảnh chính và sảnh chờ cư dân tòa Signature 1'),
    (17, 'Lễ tân tòa Signature 1'), (18, 'Khu vực thư tín'),
    (19, 'Phòng tập Gym'), (20, 'Khiêu vũ và Yoga'),
    (21, 'Phòng xông hơi & thay đồ'), (22, 'Sảnh chính Signature 2'),
    (23, 'Lễ tân tòa Signature 2'), (24, 'Sảnh chờ cư dân tòa Signature 2'),
    (25, 'Phòng tiệc cư dân & Phòng cộng đồng'), (26, 'Phòng chơi trẻ em'),
    (27, 'Sân chơi Khám Phá'), (28, 'Nhà bạt nhún'),
    (29, 'Sảnh chính và sảnh chờ cư dân tòa Signature 3'),
    (30, 'Lễ tân tòa Signature 3'), (31, 'Phòng tiệc cư dân'),
    (32, 'Không gian làm việc chung & Phòng cộng đồng'),
    (33, 'Phòng chiếu phim đa năng'),
]
LUNA_OUTDOOR = [
    (34, 'Vườn Luna'), (35, 'Cổng Luna'), (36, 'Sảnh đón'),
    (37, 'Vườn Dạ Khúc'), (38, 'Sân tắm nắng'), (39, 'Bể bơi Spa Luna'),
    (40, 'Bể Jacuzzi'), (41, 'Sân Thư Giãn'), (42, 'Hồ bơi Lấp Lánh'),
    (43, 'Sân chơi Lấp Lánh'), (44, 'Vườn BBQ Luna'),
    (45, 'Vườn thảo mộc'), (46, 'Khu phố thương mại Luna'),
]
LUNA_INDOOR = [
    (47, 'Đại sảnh tòa Signature 5'), (48, 'Lễ tân tòa Signature 5'),
    (49, 'Sảnh chờ cư dân tòa Signature 5'), (18, 'Khu vực thư tín'),
    (31, 'Phòng tiệc cư dân'),
    (32, 'Không gian làm việc chung & Phòng cộng đồng'),
    (50, 'Sảnh tiệc'), (51, 'Phòng game'), (52, 'Sân golf 3D'),
    (53, 'Đại sảnh tòa Signature 6'), (54, 'Lễ tân tòa Signature 6'),
    (55, 'Sảnh chờ cư dân tòa Signature 6'), (56, 'Sảnh đọc & Thư viện'),
    (19, 'Phòng tập Gym'), (20, 'Khiêu vũ và Yoga'),
    (21, 'Phòng xông hơi & thay đồ'),
    (57, 'Vườn trên cao & Góc thư giãn (tầng 20)'),
    (58, 'Phòng Cigar trên cao (tầng 35)'),
    (59, 'Phòng tiệc và rượu vang trên cao (tầng 35)'),
]
GREEN = [
    (60, 'Rạp chiếu phim ngoài trời'), (61, 'Công viên thú cưng'),
    (62, 'Chòi nghỉ Hoa Đăng'), (63, 'Sân chơi Kỳ Thú với Nhà cây'),
    (64, 'Khu rừng Khám Phá'), (65, 'Đường dạo trên không'),
    (66, 'Sân Vọng Cảnh'), (67, 'Khu cắm trại'), (68, 'Vườn Đom Đóm'),
    (69, 'Vườn Tái Tạo'), (70, 'Trạm sạc xe điện & Khu đỗ xe'),
    (71, 'Khu đỗ xe đạp'), (72, 'Khu đỗ xe thương mại'),
]
SPORTS = [
    (73, 'Sân tennis'), (74, 'Khán đài cổ vũ'),
    (75, 'Sân Pickleball / Sân Cầu lông'), (76, 'Sân thể thao đa năng'),
    (77, 'Sân trượt patin'), (78, 'Sân tập ngoài trời'),
    (79, 'Sân cỏ đa năng'), (80, 'Sân tập golf mini'),
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('brochure', type=Path)
    parser.add_argument('--work-dir', type=Path, required=True)
    parser.add_argument('--font-dir', type=Path,
                        default=Path('/usr/share/fonts/truetype/dejavu'))
    args = parser.parse_args()
    args.work_dir.mkdir(parents=True, exist_ok=True)
    pdfmetrics.registerFont(TTFont('Plan', str(args.font_dir / 'DejaVuSans.ttf')))
    pdfmetrics.registerFont(TTFont('PlanBold', str(args.font_dir / 'DejaVuSans-Bold.ttf')))
    records = SOLE_OUTDOOR + SOLE_INDOOR + LUNA_OUTDOOR + LUNA_INDOOR + GREEN + SPORTS
    assert {number for number, _ in records} == set(range(1, 81))
    assert len(records) == 86  # Six indoor facilities reuse the original plan's numbers.

    source = fitz.open(args.brochure)
    page = source[6]
    pix = page.get_pixmap(matrix=fitz.Matrix(3840 / page.rect.width,
                                           3840 / page.rect.width), alpha=False)
    original = Image.frombytes('RGB', (pix.width, pix.height), pix.samples)
    # Crop the artwork from the spread; preserve every tower and facility marker.
    artwork = original.crop((0, 430, 2180, 2220))
    paper = '#%02x%02x%02x' % original.getpixel((20, 20))
    pdf = args.work_dir / 'masterplan-layout.pdf'
    c = canvas.Canvas(str(pdf), pagesize=(3840, 2560))
    c.setTitle('Mặt bằng cảnh quan Lumi Signature - chú giải tiếng Việt')
    c.setAuthor('Lumi Hanoi')
    c.setFillColor(HexColor(paper))
    c.rect(0, 0, 3840, 2560, fill=1, stroke=0)

    def text(x, y, value, size=24, bold=False, color='#293e34'):
        c.setFillColor(HexColor(color))
        c.setFont('PlanBold' if bold else 'Plan', size)
        c.drawString(x, 2560 - y, value)

    def wrap(value, width=680):
        lines, line = [], ''
        for word in value.split():
            candidate = f'{line} {word}'.strip()
            if line and pdfmetrics.stringWidth(candidate, 'Plan', 24) > width:
                lines.append(line)
                line = word
            else:
                line = candidate
        return lines + [line]

    def entries(x, y, records, color, indoor=False):
        for number, label in records:
            cy = 2560 - y + 8
            c.setFillColor(HexColor(color))
            if indoor:
                path = c.beginPath()
                path.moveTo(x + 18, cy + 21)
                path.lineTo(x + 39, cy)
                path.lineTo(x + 18, cy - 21)
                path.lineTo(x - 3, cy)
                path.close()
                c.drawPath(path, fill=1, stroke=0)
            else:
                c.circle(x + 18, cy, 19, fill=1, stroke=0)
            c.setFillColor(HexColor('#3a403a'))
            c.setFont('PlanBold', 19)
            c.drawCentredString(x + 18, cy - 6.5, str(number))
            lines = wrap(label)
            for line in lines:
                text(x + 52, y, line)
                y += 31
            y += 10
        return y

    def heading(x, y, value, color):
        c.setFillColor(HexColor(color))
        c.roundRect(x - 8, 2560 - y - 19, 758, 67, 12, fill=1, stroke=0)
        text(x + 16, y + 2, value, 32, True)
        return y + 75

    text(82, 112, 'LUMI HANOI', 30, True)
    text(80, 221, 'Mặt bằng cảnh quan', 69, True)
    text(80, 307, 'Lumi Signature', 69, True)
    text(84, 373, 'S1  ·  S2  ·  S3  ·  S5  ·  S6', 31, color='#766752')
    c.drawImage(ImageReader(artwork), 35, 2560 - 440 - 1790 * 2140 / 2180,
                width=2140, height=1790 * 2140 / 2180, mask='auto')
    text(85, 2300, 'SOLE ZONE', 28, True)
    text(85, 2352, 'S1 · S2 · S3', 27)
    text(720, 2300, 'LUNA ZONE', 28, True)
    text(720, 2352, 'S5 · S6', 27)
    text(1330, 2300, 'CHÚ GIẢI', 28, True)
    text(1330, 2352, 'Số trên sơ đồ ↔ tên tiện ích', 27)
    c.setStrokeColor(HexColor('#d5d1c6'))
    c.setLineWidth(2)
    c.line(2185, 160, 2185, 2460)
    text(2230, 95, 'CHÚ GIẢI TIỆN ÍCH', 26, True)
    left = heading(2230, 164, 'SOLE ZONE', '#e7d7bd')
    text(2230, left, 'Ngoài trời', 25, True)
    left = entries(2230, left + 45, SOLE_OUTDOOR, '#e7d7bd')
    text(2230, left + 14, 'Trong nhà', 25, True)
    left = entries(2230, left + 59, SOLE_INDOOR, '#e7d7bd', True)
    left = heading(2230, left + 45, 'LÁ PHỔI XANH', '#d1dbc4')
    left = entries(2230, left, GREEN, '#d1dbc4')
    right = heading(3030, 164, 'LUNA ZONE', '#dcd3e8')
    text(3030, right, 'Ngoài trời', 25, True)
    right = entries(3030, right + 45, LUNA_OUTDOOR, '#dcd3e8')
    text(3030, right + 14, 'Trong nhà', 25, True)
    right = entries(3030, right + 59, LUNA_INDOOR, '#dcd3e8', True)
    right = heading(3030, right + 45, 'THỂ THAO', '#e5dfcf')
    right = entries(3030, right, SPORTS, '#e5dfcf')
    print('Legend bottom:', left, right)
    assert max(left, right) < 2440, 'Legend would overlap the footer'
    c.setStrokeColor(HexColor('#d5d1c6'))
    c.line(82, 116, 3760, 116)
    text(82, 2490, 'Sơ đồ cảnh quan và tiện ích phân khu Signature; vị trí mang tính tương đối.',
         24, color='#66665d')
    text(3480, 2490, 'lumi-hanoi.com', 24, True)
    c.showPage()
    c.save()

    rendered = fitz.open(pdf)
    assert 'Sân tập golf mini' in rendered[0].get_text()
    pix = rendered[0].get_pixmap(alpha=False)
    image = Image.frombytes('RGB', (pix.width, pix.height), pix.samples)
    image.save(args.work_dir / 'masterplan-layout-3840.png')
    target_dir = ROOT / 'assets/media/masterplan'
    for width, quality in [(640, 80), (1280, 82), (1920, 78), (3840, 90)]:
        variant = image if width == 3840 else image.resize(
            (width, round(width * 2560 / 3840)), Image.Resampling.LANCZOS)
        target = target_dir / f'lumi-hanoi-masterplan-{width}.webp'
        variant.save(target, 'WEBP', quality=quality, method=6)
        if width == 1280:
            # Keep historical image URLs useful without serving 4K on page load.
            (target_dir / 'lumi-hanoi-masterplan.webp').write_bytes(target.read_bytes())
        print(target.name, variant.size, target.stat().st_size)


if __name__ == '__main__':
    main()
